version: "2"


services:
   build:
      privileged: true
      container_name: build
      build: build
      hostname: build
      tty: true
      volumes:
        - .:/home/rosemary

   harness:
      privileged: true
      container_name: harness
      build: harness
      hostname: harness
      tty: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - .:/home/rosemary

   blog:
      container_name: blog
      build: blog
      hostname: blog
      tty: true
      volumes:
        - .:/home/rosemary

   database:
      container_name: database
      build: database
      hostname: database
      tty: true
      volumes:
        - .:/home/rosemary

   spire:
      container_name: spire
      build: spire
      hostname: spire
      tty: true
      volumes:
        - .:/home/rosemary
