version: "2"


services:
   harness:
      privileged: true
      container_name: harness
      build: harness
      hostname: harness
      tty: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - .:/home/rosemary

   blog:
      container_name: blog
      build: blog
      hostname: blog
      tty: true

   database:
      container_name: database
      build: database
      hostname: database
      tty: true

   control_plane:
      container_name: control_plane
      build: control_plane
      hostname: control_plane
      tty: true
